apiVersion: apps/v1
kind: Deployment

metadata:
  name: mlapp-deployment
  labels:
    app: mlapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlapp
  template:
    metadata:
      labels:
        app: mlapp
    spec:
      containers:
      - name: mlapp-container
        image: suryanshmahiradh/mlops:latest
        ports:
        - containerPort: 5000
